#!/bin/bash

# Run batch 
# echo "Start time : $(date +"%T")" && echo "Start time : $(date +"%T")" && aws

echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050463 FS_USM_0050463 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050466 FS_USM_0050466 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050467 FS_USM_0050467 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050468 FS_USM_0050468 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050469 FS_USM_0050469 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050470 FS_USM_0050470 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050477 FS_USM_0050477 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050480 FS_USM_0050480 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050481 FS_USM_0050481 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050482 FS_USM_0050482 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050483 FS_USM_0050483 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050485 FS_USM_0050485 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050486 FS_USM_0050486 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050487 FS_USM_0050487 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050488 FS_USM_0050488 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050489 FS_USM_0050489 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050490 FS_USM_0050490 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050491 FS_USM_0050491 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050492 FS_USM_0050492 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050493 FS_USM_0050493 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050494 FS_USM_0050494 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050496 FS_USM_0050496 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050497 FS_USM_0050497 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050498 FS_USM_0050498 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050499 FS_USM_0050499 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050500 FS_USM_0050500 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050501 FS_USM_0050501 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050502 FS_USM_0050502 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050503 FS_USM_0050503 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050504 FS_USM_0050504 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050505 FS_USM_0050505 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050507 FS_USM_0050507 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050509 FS_USM_0050509 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050510 FS_USM_0050510 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050511 FS_USM_0050511 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050514 FS_USM_0050514 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050515 FS_USM_0050515 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050516 FS_USM_0050516 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050518 FS_USM_0050518 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050519 FS_USM_0050519 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050520 FS_USM_0050520 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050521 FS_USM_0050521 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050523 FS_USM_0050523 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050524 FS_USM_0050524 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050525 FS_USM_0050525 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050526 FS_USM_0050526 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050527 FS_USM_0050527 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050528 FS_USM_0050528 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050529 FS_USM_0050529 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050530 FS_USM_0050530 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050531 FS_USM_0050531 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/USM_0050532 FS_USM_0050532 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050551 FS_Yale_0050551 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050552 FS_Yale_0050552 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050553 FS_Yale_0050553 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050554 FS_Yale_0050554 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050555 FS_Yale_0050555 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050556 FS_Yale_0050556 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050557 FS_Yale_0050557 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050558 FS_Yale_0050558 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050559 FS_Yale_0050559 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050560 FS_Yale_0050560 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050561 FS_Yale_0050561 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050562 FS_Yale_0050562 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050563 FS_Yale_0050563 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050564 FS_Yale_0050564 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050565 FS_Yale_0050565 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050566 FS_Yale_0050566 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050567 FS_Yale_0050567 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050568 FS_Yale_0050568 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050569 FS_Yale_0050569 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050570 FS_Yale_0050570 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050571 FS_Yale_0050571 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050572 FS_Yale_0050572 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050573 FS_Yale_0050573 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050574 FS_Yale_0050574 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050575 FS_Yale_0050575 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050576 FS_Yale_0050576 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050577 FS_Yale_0050577 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050578 FS_Yale_0050578 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050601 FS_Yale_0050601 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050602 FS_Yale_0050602 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050603 FS_Yale_0050603 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050604 FS_Yale_0050604 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050605 FS_Yale_0050605 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050606 FS_Yale_0050606 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050607 FS_Yale_0050607 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050608 FS_Yale_0050608 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050609 FS_Yale_0050609 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050610 FS_Yale_0050610 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050611 FS_Yale_0050611 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050612 FS_Yale_0050612 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050613 FS_Yale_0050613 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050614 FS_Yale_0050614 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050615 FS_Yale_0050615 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050616 FS_Yale_0050616 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050617 FS_Yale_0050617 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050618 FS_Yale_0050618 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050619 FS_Yale_0050619 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050620 FS_Yale_0050620 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050621 FS_Yale_0050621 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050622 FS_Yale_0050622 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050623 FS_Yale_0050623 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050624 FS_Yale_0050624 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050625 FS_Yale_0050625 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050626 FS_Yale_0050626 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050627 FS_Yale_0050627 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Yale_0050628 FS_Yale_0050628 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050642 FS_CMU_a_0050642 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050643 FS_CMU_b_0050643 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050644 FS_CMU_b_0050644 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050645 FS_CMU_b_0050645 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050646 FS_CMU_a_0050646 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050647 FS_CMU_a_0050647 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050648 FS_CMU_b_0050648 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050649 FS_CMU_a_0050649 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050650 FS_CMU_b_0050650 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050651 FS_CMU_b_0050651 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050652 FS_CMU_b_0050652 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050653 FS_CMU_a_0050653 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050654 FS_CMU_a_0050654 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050655 FS_CMU_b_0050655 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050656 FS_CMU_a_0050656 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050657 FS_CMU_b_0050657 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050658 FS_CMU_b_0050658 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050659 FS_CMU_a_0050659 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050660 FS_CMU_a_0050660 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050661 FS_CMU_b_0050661 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050663 FS_CMU_a_0050663 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050664 FS_CMU_a_0050664 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050665 FS_CMU_a_0050665 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050666 FS_CMU_a_0050666 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050667 FS_CMU_b_0050667 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_a_0050668 FS_CMU_a_0050668 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/CMU_b_0050669 FS_CMU_b_0050669 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050682 FS_Leuven_1_0050682 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050683 FS_Leuven_1_0050683 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050685 FS_Leuven_1_0050685 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050686 FS_Leuven_1_0050686 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050687 FS_Leuven_1_0050687 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050688 FS_Leuven_1_0050688 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050689 FS_Leuven_1_0050689 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050690 FS_Leuven_1_0050690 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050691 FS_Leuven_1_0050691 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050692 FS_Leuven_1_0050692 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050693 FS_Leuven_1_0050693 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050694 FS_Leuven_1_0050694 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050695 FS_Leuven_1_0050695 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050696 FS_Leuven_1_0050696 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050697 FS_Leuven_1_0050697 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050698 FS_Leuven_1_0050698 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050699 FS_Leuven_1_0050699 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050700 FS_Leuven_1_0050700 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050701 FS_Leuven_1_0050701 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050702 FS_Leuven_1_0050702 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050703 FS_Leuven_1_0050703 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050704 FS_Leuven_1_0050704 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050705 FS_Leuven_1_0050705 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050706 FS_Leuven_1_0050706 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050707 FS_Leuven_1_0050707 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050708 FS_Leuven_1_0050708 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050709 FS_Leuven_1_0050709 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050710 FS_Leuven_1_0050710 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_1_0050711 FS_Leuven_1_0050711 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_2_0050722 FS_Leuven_2_0050722 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Leuven_2_0050723 FS_Leuven_2_0050723 --recursive --no-sign-request --quiet


