#!/bin/bash

# Run batch 
# echo "Start time : $(date +"%T")" && aws
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051248 FS_UCLA_1_0051248 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051249 FS_UCLA_1_0051249 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051250 FS_UCLA_1_0051250 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051251 FS_UCLA_1_0051251 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051252 FS_UCLA_1_0051252 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051253 FS_UCLA_1_0051253 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051254 FS_UCLA_1_0051254 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051255 FS_UCLA_1_0051255 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051256 FS_UCLA_1_0051256 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051257 FS_UCLA_1_0051257 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051258 FS_UCLA_1_0051258 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051260 FS_UCLA_1_0051260 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051261 FS_UCLA_1_0051261 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051262 FS_UCLA_1_0051262 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051263 FS_UCLA_1_0051263 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051264 FS_UCLA_1_0051264 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051265 FS_UCLA_1_0051265 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051266 FS_UCLA_1_0051266 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051267 FS_UCLA_1_0051267 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051268 FS_UCLA_1_0051268 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051269 FS_UCLA_1_0051269 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051271 FS_UCLA_1_0051271 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051272 FS_UCLA_1_0051272 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051273 FS_UCLA_1_0051273 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051274 FS_UCLA_1_0051274 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051275 FS_UCLA_1_0051275 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051276 FS_UCLA_1_0051276 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051277 FS_UCLA_1_0051277 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051278 FS_UCLA_1_0051278 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051279 FS_UCLA_1_0051279 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051280 FS_UCLA_1_0051280 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051281 FS_UCLA_1_0051281 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051282 FS_UCLA_1_0051282 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051291 FS_UCLA_2_0051291 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051292 FS_UCLA_2_0051292 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051293 FS_UCLA_2_0051293 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051294 FS_UCLA_2_0051294 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051295 FS_UCLA_2_0051295 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051296 FS_UCLA_2_0051296 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051297 FS_UCLA_2_0051297 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051298 FS_UCLA_2_0051298 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051299 FS_UCLA_2_0051299 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051300 FS_UCLA_2_0051300 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051301 FS_UCLA_2_0051301 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051302 FS_UCLA_2_0051302 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051303 FS_UCLA_2_0051303 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051304 FS_UCLA_2_0051304 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051305 FS_UCLA_2_0051305 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051306 FS_UCLA_2_0051306 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051307 FS_UCLA_2_0051307 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051308 FS_UCLA_2_0051308 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051309 FS_UCLA_2_0051309 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051311 FS_UCLA_2_0051311 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051312 FS_UCLA_2_0051312 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051313 FS_UCLA_2_0051313 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051314 FS_UCLA_2_0051314 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051315 FS_UCLA_2_0051315 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051316 FS_UCLA_2_0051316 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_2_0051317 FS_UCLA_2_0051317 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051318 FS_MaxMun_a_0051318 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051319 FS_MaxMun_a_0051319 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051320 FS_MaxMun_a_0051320 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051321 FS_MaxMun_a_0051321 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_b_0051322 FS_MaxMun_b_0051322 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_b_0051323 FS_MaxMun_b_0051323 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_b_0051324 FS_MaxMun_b_0051324 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_b_0051325 FS_MaxMun_b_0051325 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_b_0051326 FS_MaxMun_b_0051326 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_b_0051327 FS_MaxMun_b_0051327 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051328 FS_MaxMun_c_0051328 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051329 FS_MaxMun_d_0051329 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051330 FS_MaxMun_d_0051330 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051331 FS_MaxMun_d_0051331 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051332 FS_MaxMun_c_0051332 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051333 FS_MaxMun_c_0051333 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051334 FS_MaxMun_c_0051334 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051335 FS_MaxMun_c_0051335 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051336 FS_MaxMun_c_0051336 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051338 FS_MaxMun_c_0051338 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051339 FS_MaxMun_c_0051339 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051340 FS_MaxMun_c_0051340 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051341 FS_MaxMun_c_0051341 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051342 FS_MaxMun_c_0051342 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051343 FS_MaxMun_c_0051343 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051344 FS_MaxMun_c_0051344 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051345 FS_MaxMun_c_0051345 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051346 FS_MaxMun_c_0051346 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051347 FS_MaxMun_c_0051347 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_c_0051348 FS_MaxMun_c_0051348 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051349 FS_MaxMun_d_0051349 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051350 FS_MaxMun_d_0051350 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051351 FS_MaxMun_d_0051351 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051352 FS_MaxMun_d_0051352 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051353 FS_MaxMun_d_0051353 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051354 FS_MaxMun_d_0051354 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051355 FS_MaxMun_d_0051355 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051356 FS_MaxMun_d_0051356 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051357 FS_MaxMun_d_0051357 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051358 FS_MaxMun_d_0051358 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051359 FS_MaxMun_d_0051359 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051360 FS_MaxMun_d_0051360 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_d_0051361 FS_MaxMun_d_0051361 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051362 FS_MaxMun_a_0051362 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051363 FS_MaxMun_a_0051363 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051364 FS_MaxMun_a_0051364 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051365 FS_MaxMun_a_0051365 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051369 FS_MaxMun_a_0051369 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051370 FS_MaxMun_a_0051370 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051373 FS_MaxMun_a_0051373 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051456 FS_Caltech_0051456 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051457 FS_Caltech_0051457 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051458 FS_Caltech_0051458 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051459 FS_Caltech_0051459 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051460 FS_Caltech_0051460 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051461 FS_Caltech_0051461 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051462 FS_Caltech_0051462 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051463 FS_Caltech_0051463 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051464 FS_Caltech_0051464 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051465 FS_Caltech_0051465 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051466 FS_Caltech_0051466 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051467 FS_Caltech_0051467 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051468 FS_Caltech_0051468 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051469 FS_Caltech_0051469 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051470 FS_Caltech_0051470 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051471 FS_Caltech_0051471 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051472 FS_Caltech_0051472 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051473 FS_Caltech_0051473 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051474 FS_Caltech_0051474 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051476 FS_Caltech_0051476 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051477 FS_Caltech_0051477 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051478 FS_Caltech_0051478 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051479 FS_Caltech_0051479 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051480 FS_Caltech_0051480 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051481 FS_Caltech_0051481 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051482 FS_Caltech_0051482 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051483 FS_Caltech_0051483 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051484 FS_Caltech_0051484 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051485 FS_Caltech_0051485 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051486 FS_Caltech_0051486 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051487 FS_Caltech_0051487 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051488 FS_Caltech_0051488 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051489 FS_Caltech_0051489 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051490 FS_Caltech_0051490 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051491 FS_Caltech_0051491 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051492 FS_Caltech_0051492 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Caltech_0051493 FS_Caltech_0051493 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051556 FS_SBL_0051556 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051557 FS_SBL_0051557 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051558 FS_SBL_0051558 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051559 FS_SBL_0051559 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051560 FS_SBL_0051560 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051561 FS_SBL_0051561 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051562 FS_SBL_0051562 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051563 FS_SBL_0051563 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051564 FS_SBL_0051564 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051565 FS_SBL_0051565 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051566 FS_SBL_0051566 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051567 FS_SBL_0051567 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051568 FS_SBL_0051568 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051569 FS_SBL_0051569 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051570 FS_SBL_0051570 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051571 FS_SBL_0051571 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051572 FS_SBL_0051572 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051573 FS_SBL_0051573 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051574 FS_SBL_0051574 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051575 FS_SBL_0051575 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051576 FS_SBL_0051576 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051577 FS_SBL_0051577 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051578 FS_SBL_0051578 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051579 FS_SBL_0051579 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051580 FS_SBL_0051580 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051581 FS_SBL_0051581 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051582 FS_SBL_0051582 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051583 FS_SBL_0051583 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051584 FS_SBL_0051584 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/SBL_0051585 FS_SBL_0051585 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051606 FS_MaxMun_a_0051606 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/MaxMun_a_0051607 FS_MaxMun_a_0051607 --recursive --no-sign-request --quiet




