#!/bin/bash

# Run batch 
# echo "Start time : $(date +"%T")" && aws

echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051056 FS_NYU_0051056 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051057 FS_NYU_0051057 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051058 FS_NYU_0051058 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051059 FS_NYU_0051059 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051060 FS_NYU_0051060 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051061 FS_NYU_0051061 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051062 FS_NYU_0051062 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051063 FS_NYU_0051063 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051064 FS_NYU_0051064 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051065 FS_NYU_0051065 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051066 FS_NYU_0051066 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051067 FS_NYU_0051067 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051068 FS_NYU_0051068 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051069 FS_NYU_0051069 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051070 FS_NYU_0051070 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051071 FS_NYU_0051071 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051072 FS_NYU_0051072 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051073 FS_NYU_0051073 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051074 FS_NYU_0051074 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051075 FS_NYU_0051075 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051076 FS_NYU_0051076 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051077 FS_NYU_0051077 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051078 FS_NYU_0051078 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051079 FS_NYU_0051079 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051080 FS_NYU_0051080 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051081 FS_NYU_0051081 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051082 FS_NYU_0051082 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051083 FS_NYU_0051083 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051084 FS_NYU_0051084 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051085 FS_NYU_0051085 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051086 FS_NYU_0051086 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051087 FS_NYU_0051087 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051088 FS_NYU_0051088 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051089 FS_NYU_0051089 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051090 FS_NYU_0051090 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051091 FS_NYU_0051091 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051093 FS_NYU_0051093 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051094 FS_NYU_0051094 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051095 FS_NYU_0051095 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051096 FS_NYU_0051096 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051097 FS_NYU_0051097 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051098 FS_NYU_0051098 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051099 FS_NYU_0051099 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051100 FS_NYU_0051100 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051101 FS_NYU_0051101 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051102 FS_NYU_0051102 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051103 FS_NYU_0051103 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051104 FS_NYU_0051104 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051105 FS_NYU_0051105 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051106 FS_NYU_0051106 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051107 FS_NYU_0051107 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051109 FS_NYU_0051109 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051110 FS_NYU_0051110 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051111 FS_NYU_0051111 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051112 FS_NYU_0051112 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051113 FS_NYU_0051113 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051114 FS_NYU_0051114 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051116 FS_NYU_0051116 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051117 FS_NYU_0051117 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051118 FS_NYU_0051118 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051121 FS_NYU_0051121 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051122 FS_NYU_0051122 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051123 FS_NYU_0051123 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051124 FS_NYU_0051124 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051126 FS_NYU_0051126 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051127 FS_NYU_0051127 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051128 FS_NYU_0051128 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051129 FS_NYU_0051129 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051130 FS_NYU_0051130 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051131 FS_NYU_0051131 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051132 FS_Trinity_0051132 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051133 FS_Trinity_0051133 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051134 FS_Trinity_0051134 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051135 FS_Trinity_0051135 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051136 FS_Trinity_0051136 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051137 FS_Trinity_0051137 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051138 FS_Trinity_0051138 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051139 FS_Trinity_0051139 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051140 FS_Trinity_0051140 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051141 FS_Trinity_0051141 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Trinity_0051142 FS_Trinity_0051142 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051146 FS_NYU_0051146 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051147 FS_NYU_0051147 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051148 FS_NYU_0051148 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051149 FS_NYU_0051149 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051150 FS_NYU_0051150 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051151 FS_NYU_0051151 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051152 FS_NYU_0051152 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051153 FS_NYU_0051153 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051154 FS_NYU_0051154 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051155 FS_NYU_0051155 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051156 FS_NYU_0051156 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/NYU_0051159 FS_NYU_0051159 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051160 FS_Stanford_0051160 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051161 FS_Stanford_0051161 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051162 FS_Stanford_0051162 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051163 FS_Stanford_0051163 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051164 FS_Stanford_0051164 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051165 FS_Stanford_0051165 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051166 FS_Stanford_0051166 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051167 FS_Stanford_0051167 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051168 FS_Stanford_0051168 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051169 FS_Stanford_0051169 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051170 FS_Stanford_0051170 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051171 FS_Stanford_0051171 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051172 FS_Stanford_0051172 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051173 FS_Stanford_0051173 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051174 FS_Stanford_0051174 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051175 FS_Stanford_0051175 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051177 FS_Stanford_0051177 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051178 FS_Stanford_0051178 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051179 FS_Stanford_0051179 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051180 FS_Stanford_0051180 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051181 FS_Stanford_0051181 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051182 FS_Stanford_0051182 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051183 FS_Stanford_0051183 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051184 FS_Stanford_0051184 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051185 FS_Stanford_0051185 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051186 FS_Stanford_0051186 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051187 FS_Stanford_0051187 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051188 FS_Stanford_0051188 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051189 FS_Stanford_0051189 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051190 FS_Stanford_0051190 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051191 FS_Stanford_0051191 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051192 FS_Stanford_0051192 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051193 FS_Stanford_0051193 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051194 FS_Stanford_0051194 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051195 FS_Stanford_0051195 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051196 FS_Stanford_0051196 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051197 FS_Stanford_0051197 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051198 FS_Stanford_0051198 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/Stanford_0051199 FS_Stanford_0051199 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051201 FS_UCLA_1_0051201 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051202 FS_UCLA_1_0051202 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051203 FS_UCLA_1_0051203 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051204 FS_UCLA_1_0051204 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051205 FS_UCLA_1_0051205 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051206 FS_UCLA_1_0051206 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051207 FS_UCLA_1_0051207 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051208 FS_UCLA_1_0051208 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051209 FS_UCLA_1_0051209 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051210 FS_UCLA_1_0051210 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051211 FS_UCLA_1_0051211 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051212 FS_UCLA_1_0051212 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051213 FS_UCLA_1_0051213 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051214 FS_UCLA_1_0051214 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051215 FS_UCLA_1_0051215 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051216 FS_UCLA_1_0051216 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051217 FS_UCLA_1_0051217 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051218 FS_UCLA_1_0051218 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051219 FS_UCLA_1_0051219 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051220 FS_UCLA_1_0051220 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051221 FS_UCLA_1_0051221 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051222 FS_UCLA_1_0051222 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051223 FS_UCLA_1_0051223 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051224 FS_UCLA_1_0051224 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051225 FS_UCLA_1_0051225 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051226 FS_UCLA_1_0051226 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051227 FS_UCLA_1_0051227 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051228 FS_UCLA_1_0051228 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051229 FS_UCLA_1_0051229 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051230 FS_UCLA_1_0051230 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051231 FS_UCLA_1_0051231 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051234 FS_UCLA_1_0051234 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051235 FS_UCLA_1_0051235 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051236 FS_UCLA_1_0051236 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051237 FS_UCLA_1_0051237 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051238 FS_UCLA_1_0051238 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051239 FS_UCLA_1_0051239 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051240 FS_UCLA_1_0051240 --recursive --no-sign-request --quiet
echo "Start time : $(date +"%T")" && aws s3 cp s3://fcp-indi/data/Projects/ABIDE_Initiative/Outputs/freesurfer/5.1/UCLA_1_0051241 FS_UCLA_1_0051241 --recursive --no-sign-request --quiet







